from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

metadata = sa.MetaData()

patrol_batch = sa.Table(
    "t_patrol_batch",
    metadata,
    sa.Column("batch_id", sa.String(64), primary_key=True),
    sa.Column("idempotency_key", sa.String(191), nullable=False),
    sa.Column("trigger_type", sa.String(32), nullable=False),
    sa.Column("business_date", sa.Date(), nullable=False),
    sa.Column("scope_json", mysql.JSON(), nullable=False),
    sa.Column("scope_hash", sa.CHAR(64), nullable=False),
    sa.Column("rule_bundle_version", sa.String(128), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("total_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("pending_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("running_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("succeeded_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("failed_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("started_at", mysql.DATETIME(fsp=6)),
    sa.Column("finished_at", mysql.DATETIME(fsp=6)),
)

patrol_job = sa.Table(
    "t_patrol_job",
    metadata,
    sa.Column("job_id", sa.String(64), primary_key=True),
    sa.Column("batch_id", sa.String(64), nullable=False),
    sa.Column("request_id", sa.String(191), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("site_code", sa.String(32), nullable=False),
    sa.Column("parent_asin", sa.String(32), nullable=False),
    sa.Column("parent_seller_sku", sa.String(128), nullable=False),
    sa.Column("shop_account_ref", sa.String(128), nullable=False),
    sa.Column("job_type", sa.String(32), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("payload_json", mysql.JSON(), nullable=False),
    sa.Column("result_ref", sa.String(64)),
    sa.Column("retry_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("max_retry", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("next_retry_at", mysql.DATETIME(fsp=6)),
    sa.Column("locked_by", sa.String(128)),
    sa.Column("locked_at", mysql.DATETIME(fsp=6)),
    sa.Column("last_error_code", sa.String(64)),
    sa.Column("last_error_message", sa.Text()),
    sa.Column("created_at", mysql.DATETIME(fsp=6)),
)

patrol_scheduler_lock = sa.Table(
    "t_patrol_scheduler_lock",
    metadata,
    sa.Column("lock_name", sa.String(128), primary_key=True),
    sa.Column("holder_id", sa.String(128), nullable=False),
    sa.Column("acquired_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("renewed_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("version", mysql.BIGINT(unsigned=True), nullable=False),
)

patrol_run = sa.Table(
    "t_patrol_run",
    metadata,
    sa.Column("run_id", sa.String(64), primary_key=True),
    sa.Column("job_id", sa.String(64), nullable=False),
    sa.Column("batch_id", sa.String(64), nullable=False),
    sa.Column("request_id", sa.String(191), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("trigger_type", sa.String(32), nullable=False),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("rule_versions_json", mysql.JSON(), nullable=False),
    sa.Column("fact_snapshot_id", sa.String(64)),
    sa.Column("signal_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("data_gap_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("started_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("finished_at", mysql.DATETIME(fsp=6)),
    sa.Column("error_code", sa.String(64)),
    sa.Column("error_message", sa.Text()),
)

patrol_fact_snapshot = sa.Table(
    "t_patrol_fact_snapshot",
    metadata,
    sa.Column("snapshot_id", sa.String(64), primary_key=True),
    sa.Column("run_id", sa.String(64), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("as_of", sa.Date(), nullable=False),
    sa.Column("window_start", mysql.DATETIME(fsp=6)),
    sa.Column("window_end", mysql.DATETIME(fsp=6)),
    sa.Column("content_hash", sa.CHAR(64), nullable=False),
    sa.Column("quality_status", sa.String(24), nullable=False),
    sa.Column("completeness_score", sa.Numeric(5, 2)),
    sa.Column("source_refs_json", mysql.JSON(), nullable=False),
    sa.Column("data_gaps_json", mysql.JSON(), nullable=False),
    sa.Column("normalized_summary_json", mysql.JSON(), nullable=False),
    sa.Column("raw_reference_json", mysql.JSON()),
)

patrol_raw_fact = sa.Table(
    "t_patrol_raw_fact",
    metadata,
    sa.Column("raw_fact_id", sa.String(64), primary_key=True),
    sa.Column("run_id", sa.String(64), nullable=False),
    sa.Column("snapshot_id", sa.String(64)),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("as_of_date", sa.Date(), nullable=False),
    sa.Column("fact_key", sa.String(64), nullable=False),
    sa.Column("tool_name", sa.String(128), nullable=False),
    sa.Column("request_hash", sa.CHAR(64), nullable=False),
    sa.Column("request_json", mysql.JSON(), nullable=False),
    sa.Column("response_content_hash", sa.CHAR(64)),
    sa.Column("response_json", mysql.JSON(none_as_null=True)),
    sa.Column("extracted_data_json", mysql.JSON(none_as_null=True)),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("is_core", sa.Boolean(), nullable=False),
    sa.Column("row_count", mysql.INTEGER(unsigned=True)),
    sa.Column("latency_ms", mysql.INTEGER(unsigned=True)),
    sa.Column("warning", sa.Text()),
    sa.Column("error_code", sa.String(64)),
    sa.Column("error_message", sa.Text()),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("reused_from_raw_fact_id", sa.String(64)),
    sa.Column("created_at", mysql.DATETIME(fsp=6)),
)

patrol_signal = sa.Table(
    "t_patrol_signal",
    metadata,
    sa.Column("signal_id", sa.String(64), primary_key=True),
    sa.Column("dedup_key", sa.CHAR(64), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("issue_code", sa.String(64), nullable=False),
    sa.Column("child_scope_key", sa.String(191), nullable=False),
    sa.Column("signal_type", sa.String(32), nullable=False),
    sa.Column("severity", sa.String(24), nullable=False),
    sa.Column("signal_state", sa.String(32), nullable=False),
    sa.Column("action_timing_status", sa.String(32), nullable=False),
    sa.Column("economic_currency", sa.String(16)),
    sa.Column("economic_amount", sa.Numeric(18, 4)),
    sa.Column("economic_window", sa.String(32), nullable=False),
    sa.Column("constraint_flags_json", mysql.JSON(), nullable=False),
    sa.Column("execution_readiness", sa.String(32), nullable=False),
    sa.Column("diagnosis_json", mysql.JSON(), nullable=False),
    sa.Column("handoff_json", mysql.JSON()),
    sa.Column("signal_payload_json", mysql.JSON(), nullable=False),
    sa.Column("first_detected_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("last_detected_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("last_scan_run_id", sa.String(64), nullable=False),
    sa.Column("recurrence_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("consecutive_miss_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("next_inspection_at", mysql.DATETIME(fsp=6)),
    sa.Column("valid_until", mysql.DATETIME(fsp=6)),
    sa.Column("version", mysql.BIGINT(unsigned=True), nullable=False),
)

patrol_signal_occurrence = sa.Table(
    "t_patrol_signal_occurrence",
    metadata,
    sa.Column("occurrence_id", sa.String(64), primary_key=True),
    sa.Column("signal_id", sa.String(64), nullable=False),
    sa.Column("run_id", sa.String(64), nullable=False),
    sa.Column("snapshot_id", sa.String(64)),
    sa.Column("occurrence_type", sa.String(24), nullable=False),
    sa.Column("severity", sa.String(24)),
    sa.Column("evidence_refs_json", mysql.JSON(), nullable=False),
    sa.Column("details_json", mysql.JSON(), nullable=False),
    sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_delivery_outbox = sa.Table(
    "t_patrol_delivery_outbox",
    metadata,
    sa.Column("outbox_id", sa.String(64), primary_key=True),
    sa.Column("aggregate_type", sa.String(64), nullable=False),
    sa.Column("aggregate_id", sa.String(64), nullable=False),
    sa.Column("aggregate_version", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("payload_hash", sa.CHAR(64), nullable=False),
    sa.Column("payload_json", mysql.JSON(), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("retry_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("max_retry", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("next_retry_at", mysql.DATETIME(fsp=6)),
    sa.Column("locked_by", sa.String(128)),
    sa.Column("locked_at", mysql.DATETIME(fsp=6)),
    sa.Column("last_error", sa.Text()),
    sa.Column("delivery_ack_json", mysql.JSON()),
    sa.Column("created_at", mysql.DATETIME(fsp=6)),
    sa.Column("published_at", mysql.DATETIME(fsp=6)),
    sa.UniqueConstraint(
        "aggregate_type",
        "aggregate_id",
        "aggregate_version",
        name="ux_patrol_outbox_aggregate_version",
    ),
)

patrol_feedback_inbox = sa.Table(
    "t_patrol_feedback_inbox",
    metadata,
    sa.Column("event_id", sa.String(128), primary_key=True),
    sa.Column("signal_id", sa.String(64), nullable=False),
    sa.Column("signal_version", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("event_type", sa.String(64), nullable=False),
    sa.Column("source_system", sa.String(128), nullable=False),
    sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("payload_hash", sa.CHAR(64), nullable=False),
    sa.Column("payload_json", mysql.JSON(), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("result_json", mysql.JSON()),
    sa.Column("error_message", sa.Text()),
    sa.Column("received_at", mysql.DATETIME(fsp=6)),
    sa.Column("applied_at", mysql.DATETIME(fsp=6)),
)

patrol_review = sa.Table(
    "t_patrol_review",
    metadata,
    sa.Column("review_request_id", sa.String(128), primary_key=True),
    sa.Column("review_round", mysql.INTEGER(unsigned=True), primary_key=True),
    sa.Column("request_hash", sa.CHAR(64), nullable=False),
    sa.Column("patrol_batch_no", sa.String(128), nullable=False),
    sa.Column("proposal_id", sa.String(128), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("baseline_snapshot_id", sa.String(64), nullable=False),
    sa.Column("current_snapshot_id", sa.String(64)),
    sa.Column("request_json", mysql.JSON(), nullable=False),
    sa.Column("current_snapshot_json", mysql.JSON()),
    sa.Column("result_json", mysql.JSON()),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("outcome_status", sa.String(32)),
    sa.Column("error_message", sa.Text()),
    sa.Column("requested_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("completed_at", mysql.DATETIME(fsp=6)),
    sa.Column("created_at", mysql.DATETIME(fsp=6)),
)

patrol_sys_user = sa.Table(
    "t_patrol_sys_user",
    metadata,
    sa.Column(
        "user_id",
        mysql.BIGINT(unsigned=True),
        primary_key=True,
        autoincrement=False,
    ),
    sa.Column("user_name", sa.String(128), nullable=False),
    sa.Column("user_account", sa.String(128)),
    sa.Column("user_state", sa.String(64), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_user_role = sa.Table(
    "t_patrol_user_role",
    metadata,
    sa.Column("user_id", mysql.BIGINT(unsigned=True), primary_key=True),
    sa.Column("role_code", sa.String(128), primary_key=True),
    sa.Column("role_name", sa.String(128)),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_asin_owner = sa.Table(
    "t_patrol_asin_owner",
    metadata,
    sa.Column("operating_unit_id", sa.String(64), primary_key=True),
    sa.Column("assignment_key", sa.String(96), primary_key=True),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("shop_account_ref", sa.String(128), nullable=False),
    sa.Column("site_code", sa.String(32), nullable=False),
    sa.Column("parent_asin", sa.String(32), nullable=False),
    sa.Column("parent_seller_sku", sa.String(128), nullable=False),
    sa.Column("principal_user_id", mysql.BIGINT(unsigned=True)),
    sa.Column("editor_user_id", mysql.BIGINT(unsigned=True)),
    sa.Column("creator_user_id", mysql.BIGINT(unsigned=True)),
    sa.Column("source_tool", sa.String(128), nullable=False),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_category_baseline = sa.Table(
    "t_patrol_category_baseline",
    metadata,
    sa.Column("operating_unit_id", sa.String(64), primary_key=True),
    sa.Column("child_asin", sa.String(32), primary_key=True),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("parent_asin", sa.String(32), nullable=False),
    sa.Column("parent_seller_sku", sa.String(128), nullable=False),
    sa.Column("category_id", sa.String(128)),
    sa.Column("category_path", sa.String(1024), nullable=False),
    sa.Column("source_tool", sa.String(128), nullable=False),
    sa.Column("source_snapshot_id", sa.String(64)),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("first_observed_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("last_observed_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("confirmed_by", sa.String(128)),
    sa.Column("confirmed_at", mysql.DATETIME(fsp=6)),
)

patrol_product_image = sa.Table(
    "t_patrol_product_image",
    metadata,
    sa.Column("operating_unit_id", sa.String(64), primary_key=True),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("parent_asin", sa.String(32), nullable=False),
    sa.Column("parent_seller_sku", sa.String(128), nullable=False),
    sa.Column("image_url", sa.String(2048), nullable=False),
    sa.Column("source_tool", sa.String(128), nullable=False),
    sa.Column("source_fetched_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("first_observed_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("last_observed_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_operating_unit_catalog = sa.Table(
    "t_patrol_operating_unit_catalog",
    metadata,
    sa.Column("operating_unit_id", sa.String(64), primary_key=True),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("site_code", sa.String(32), nullable=False),
    sa.Column("parent_asin", sa.String(32), nullable=False),
    sa.Column("parent_seller_sku", sa.String(128), nullable=False),
    sa.Column("shop_account_ref", sa.String(128), nullable=False),
    sa.Column("owner_user_ids_json", mysql.JSON(), nullable=False),
    sa.Column("source_tool", sa.String(128), nullable=False),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.UniqueConstraint(
        "shop_id",
        "site_code",
        "parent_asin",
        "parent_seller_sku",
        name="ux_patrol_catalog_business_key",
    ),
)

patrol_listing_catalog = sa.Table(
    "t_patrol_listing_catalog",
    metadata,
    sa.Column("listing_record_id", sa.String(64), primary_key=True),
    sa.Column("shop_id", mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column("site_code", sa.String(32), nullable=False),
    sa.Column("shop_account_ref", sa.String(128), nullable=False),
    sa.Column("asin", sa.String(32), nullable=False),
    sa.Column("seller_sku", sa.String(128), nullable=False),
    sa.Column("parent_asin", sa.String(32)),
    sa.Column("parent_seller_sku", sa.String(128)),
    sa.Column("user_id", mysql.BIGINT(unsigned=True)),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("source_tool", sa.String(128), nullable=False),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.UniqueConstraint(
        "shop_id", "site_code", "asin", "seller_sku",
        name="ux_patrol_listing_catalog_child_key",
    ),
)

patrol_child_fact_task = sa.Table(
    "t_patrol_child_fact_task",
    metadata,
    sa.Column("task_id", sa.String(64), primary_key=True),
    sa.Column("task_key", sa.CHAR(64), nullable=False, unique=True),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("child_asin", sa.String(32), nullable=False),
    sa.Column("seller_sku", sa.String(128), nullable=False),
    sa.Column("domain", sa.String(32), nullable=False),
    sa.Column("tool_name", sa.String(128), nullable=False),
    sa.Column("arguments_json", mysql.JSON(), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("retry_count", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("max_retry", mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column("next_attempt_at", mysql.DATETIME(fsp=6)),
    sa.Column("locked_by", sa.String(128)),
    sa.Column("locked_at", mysql.DATETIME(fsp=6)),
    sa.Column("last_error_code", sa.String(64)),
    sa.Column("last_error_message", sa.Text()),
    sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
)

patrol_child_fact_snapshot = sa.Table(
    "t_patrol_child_fact_snapshot",
    metadata,
    sa.Column("snapshot_id", sa.String(64), primary_key=True),
    sa.Column("task_id", sa.String(64), nullable=False),
    sa.Column("operating_unit_id", sa.String(64), nullable=False),
    sa.Column("child_asin", sa.String(32), nullable=False),
    sa.Column("domain", sa.String(32), nullable=False),
    sa.Column("tool_name", sa.String(128), nullable=False),
    sa.Column("request_hash", sa.CHAR(64), nullable=False),
    sa.Column("response_content_hash", sa.CHAR(64), nullable=False),
    sa.Column("response_json", mysql.JSON(), nullable=False),
    sa.Column("extracted_data_json", mysql.JSON(), nullable=False),
    sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
    sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
)
